### PR TITLE
feat: [CHAOS-3378]: Adding service discovery as part of platform

### PR DESCRIPTION
**Pull request by Adarshkumar14**

### CODE REVIEW

**Review by shovanmaity — APPROVED** [review]
Tested `0.1.2` version on devspce no issues in the helm chart.

**Comment by avaakash** [comment]
Can you share the repository link for SDM helm charts.

**Review by kapilgarg1996 — APPROVED** [review]

**Comment by Adarshkumar14** [comment]
> Can you share the repository link for SDM helm charts.

Here is the sdm charts: https://github.com/wings-software/service-discovery/tree/release/0.8.x/chart

**Comment by shovanmaity** [comment]
> Can you share the repository link for SDM helm charts.

https://console.cloud.google.com/artifacts/docker/gcr-prod/us-west1/harness-helm-artifacts/service-discovery-manager
us-west1-docker.pkg.dev/gcr-prod/harness-helm-artifacts/service-discovery-manager:0.1.2

**Pull request merged**
